# Site settings
title:          Zurana Mehrin Ruhi
description:    "Learning. Coding. Creating."
baseurl:        ""
url:            "https://zmruhi1.github.io/"

# Author
author:
  name:              Zurana Mehrin Ruhi
  url:               https://www.linkedin.com/in/zmruhi/
  email:             zurana.mehrin.ruhi1@gmail.com

# Build settings
markdown:       kramdown
mathjax: true

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
# permalink:      /:year-:month-:day/:title
permalink:     pretty
paginate:       5
